name: Build Firmware

on:
  push:
    branches: [ motorola_r7 ]
  workflow_dispatch: # 加上这一行后，Actions 页面就会出现“Run workflow”手动运行按钮

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Compile firmware
      run: |
        chmod +x compile-with-docker.sh
        ./compile-with-docker.sh

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v4
      with:
        name: firmware-artifact
        path: build/**/*.bin
